backbone:
  config: mit_b1
  stride: [4, 2, 2, 1]
  comments: None

scheme: transwcd_dual # transwcd_single, transwcd_dual

dataset:
  root_dir: /media/zhihui/1172508c-c4a0-4673-adc9-b86bc5d0bd9e/File/Reseacher/Paper/ours/Paper5/WSCD/dataset/LEVIR_256
  name_list_dir: datasets/LEVIR
  num_classes: 2
  crop_size: 256
  rescale_range: [1.0, 1.0]


work_dir:
  dir: work_dir_LEVIR
  ckpt_dir: checkpoints
  pred_dir: predictions
  logger_dir: logger

train:
  split: train
  batch_size: 8
  max_iters: 30000
  cam_iters: 2000
  eval_iters: 500
  log_iters: 500

cam:
  bkg_score: 0.05
  scales: [1, 0.5, 1.5]

val:
  split: val
  batch_size: 1

test:
  split: test
  batch_size: 1


optimizer:
  type: AdamW
  learning_rate: 6e-5
  betas: [0.9, 0.999]
  weight_decay: 0.0001

scheduler:
  warmup_iter: 1500
  warmup_ratio: 1e-6
  power: 1.0
